name: gh-pages
on: - push
    - watch:
        types: started
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: npm install, build, and test
              run: |
                  npm ci
                  npm run build
            - name: Use Node.js 10.x
              uses: peaceiris/actions-gh-pages@v3.5.9
              env:
                  ACTIONS_DEPLOY_KEY: ${{ secrets.deploy_key }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: dist
